services:
  solr:
    build:
      context: ./solr
      dockerfile: Dockerfile
      # Deshabilitar caché durante la construcción
      args:
        - DOCKER_BUILDKIT=1
        - BUILDKIT_INLINE_CACHE=0
    container_name: solr
    ports:
      - "8983:8983"
    networks:
      app_network:
        ipv4_address: 10.10.10.2

  front:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "80:80"
    networks:
      app_network:
        ipv4_address: 10.10.10.3

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
